FROM node:24-alpine

WORKDIR /app

USER node

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node package.json package-lock.json ./
COPY --chown=node:node src ./src
COPY --chown=node:node public ./public
COPY --chown=node:node vite.config.ts ./


EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]